#########################
# Triggers.
#########################
trigger:
  - main

#########################
# Variables.
#########################
variables:
  - name: tfWorkingDir
    value: infra
  - name: serviceConnection
    value: UKDDC_Azure_Subscription

#########################
# Resources.
#########################
resources:
  repositories:
    - repository: templates
      type: git
      name: 'Azure Capability Deployment Tools/ado-yaml-templates'
      ref: main    

#########################
# Terraform.
#########################
stages:
  - template: terraform/jobs/tf-plan.yml@templates
    parameters:
          environment: dev
          rgLocation: uks
          workingDirectory: $(tfWorkingDir)
          serviceConnection: $(serviceConnection)
          rgName: alana-barrett-frew-sandbox-rg
          saName: smartassignstoragetf
          saContainerName: tfstate
          tfVersion: "1.8.5"
          planFileName: "tfplan"                    

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main' ) }}:
    - template: terraform/jobs/tf-apply.yml@templates
      parameters:
          environment: dev
          rgLocation: uks
          workingDirectory: $(tfWorkingDir)
          serviceConnection: $(serviceConnection)
          rgName: alana-barrett-frew-sandbox-rg
          saName: smartassignstoragetf
          saContainerName: tfstate
          tfVersion: "1.8.5"
      